### ISSUE TITLE
Document the host and port

### ISSUE THREAD

**Issue by tommym9** [drud/ddev-contrib#87]
Hi,

Thanks for the recipe. It would be great to add to the documentation what the host/port will be once this container is running. Just to save someone like me looking it up.

Cheers

Tom

**Comment by tommym9** [comment]
Thinking about this, it would be great if this was shown on `ddev describe` like elasticsearch does

**Comment by rfay** [comment]
@tommym9 could you please mention which recipe you're referring to?

`ddev describe` does show the configured ports with external services in recent versions of ddev.

**Comment by tommym9** [comment]
Hi @rfay,

Sorry forgot this repo is for multiple. This one is the Redis recipie: https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/redis

I'm using DDev v1.14.2 which does pull in elasticsearch ports, but not Redis.

Cheers

Tom

**Comment by rfay** [comment]
Hi @tommym9 - redis doesn't expose an HTTP port, so can be used only with a "wired" port, no way to proxy it in ddev-router. So each project has to use a unique port. That's why ddev doesn't report the redis port. I think that would be a reasonable improvement. Most things (like redis-commander) do expose an HTTP port, and that makes it pretty easy.

**Comment by rfay** [comment]
As far as the original question... the docker-compose.redis.yaml does explicitly show 
```yaml
    ports:
      - 6379
```

So that means that this setup has the redis service listening on 6379 both inside the container and exposed on the host. If someone had more than one project running (with redis) at a time, they'll have to change that to 6379:6380 or something, see https://docs.docker.com/compose/compose-file/#ports

As you know, this is ddev_contrib, so a PR to improve both the readme and the docker-compose.redis.yaml are very welcome.
